{% set version = "0.8.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sysfonts
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sysfonts_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sysfonts/sysfonts_{{ version }}.tar.gz
  sha256: 52459c34a625a049d22ea6d6ab799428b954783da04a7c4487d47684b8659f88

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}tar               # [win]
    - {{ posix }}gzip              # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - freetype                     # [not win]
  run:
    - r-base

test:
  commands:
    - $R -e "library('sysfonts')"           # [not win]
    - "\"%R%\" -e \"library('sysfonts')\""  # [win]

about:
  home: https://github.com/yixuan/sysfonts
  license: GPL-2.0-only
  summary: Loading system fonts and Google Fonts <https://fonts.google.com/> into R, in order to support other packages such as 'R2SWF' and 'showtext'.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: sysfonts
# Type: Package
# Title: Loading Fonts into R
# Version: 0.8
# Date: 2018-10-11
# Author: Yixuan Qiu and authors/contributors of the included fonts. See file AUTHORS for details.
# Maintainer: Yixuan Qiu <yixuan.qiu@cos.name>
# Description: Loading system fonts and Google Fonts <https://fonts.google.com/> into R, in order to support other packages such as 'R2SWF' and 'showtext'.
# Suggests: curl, jsonlite
# Copyright: see file COPYRIGHTS
# SystemRequirements: zlib, libpng, FreeType
# URL: https://github.com/yixuan/sysfonts
# BugReports: https://github.com/yixuan/sysfonts/issues
# License: GPL-2
# RoxygenNote: 6.1.0
# NeedsCompilation: yes
# Packaged: 2018-10-11 18:02:24 UTC; qyx
# Repository: CRAN
# Date/Publication: 2018-10-11 18:50:03 UTC
