appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FwJHJIO0B7kGSnMUQZLZCAB7ZYUezYqU9iB8i5alv30Nq+93WEHABxqtOjDi8rCOiAl//dHj8FOjPOdcqnqTYfxoGDsw0ul9QLz3PPGK41tHQFLc3Q640/N2hVoAUz+Jw5sw7Hm7ALjTArR4LfOnfOPijxEE7Lm1B9NvZI+F+ulQE8jafm1D+VuwGeYi7Mo4Jcp+S51UI6oET3Z9zNai5zfUXD3a+j4GQ6Ete6JxXupXo5/5L2juUpeV4GTGROjt9NFJNtpyARW1hkjnhSWMsp3gUQ2tuQlkxOTv62YyWiwx1R5vjt1gOfr3ViDxGabroX+gDGjvFmqOAXoc5/2CxwYD8M5Wu5w2TLIxtxYVyEjOEOBE1kY6mZcPeT6hoXI0WhCbxr912tQmxUmq8aS9nYG71/FmSE59gkWoBoInBy7zXud0gEXqjmmqBCPfIgtjH02LgKNRYwzTR3Y99v1vTrDwCsrI7ks7P0dpXZTrFwg/T7kVT/uNgAsE0qh9QxOd4W0QLMfWksxCOdJzMHkMHHl1wPQjb9WoXniIE49qUINJzqMLGCX8S3gJx6JhWh++mp2jLfLJW+KdvW+fHZya41LKjik2NBnngsuJgprGeLVt1xE0IpzNCFAlBAbCfSeCzNvfIF4O8+Web+2tb3VRkMo2Xw32yg6gszHeCEIdd1U=
